# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glenv < Formula
  desc "jump into repository folder and GitLab env. variables are automatically loaded into your shell"
  homepage "https://github.com/kiwicom/glenv"
  version "0.9.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kiwicom/glenv/releases/download/v0.9.4/glenv_0.9.4_macOS_amd64.tar.gz"
      sha256 "802060716813cbd9f3d0dcd61dd2a3fa686d358de967c0f2627d99fb5ee65375"

      def install
        bin.install "glenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kiwicom/glenv/releases/download/v0.9.4/glenv_0.9.4_macOS_arm64.tar.gz"
      sha256 "75b3ff348e1d1d3485d9edda95023acf9a8c50a2a449c323b80f3ec93f320968"

      def install
        bin.install "glenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiwicom/glenv/releases/download/v0.9.4/glenv_0.9.4_linux_arm64.tar.gz"
      sha256 "143da0b5653ec3956a745d2c71e2c84a158155c87620c9916b915cda41a26ad6"

      def install
        bin.install "glenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kiwicom/glenv/releases/download/v0.9.4/glenv_0.9.4_linux_adm64.tar.gz"
      sha256 "f9c184a6f90e6bbcaf8d63867b3967c957c903ed21dd839128fee05dc188c440"

      def install
        bin.install "glenv"
      end
    end
  end
end
