# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glenv < Formula
  desc "jump into repository folder and GitLab env. variables are automatically loaded into your shell"
  homepage "https://github.com/kiwicom/glenv"
  version "0.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kiwicom/glenv/releases/download/v0.6/glenv_0.6_Darwin_x86_64.tar.gz"
      sha256 "9e3b89860d6f09cb319e544f7e11de4ccd8cde89a3ea2bec8834cb141ac19223"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kiwicom/glenv/releases/download/v0.6/glenv_0.6_Darwin_arm64.tar.gz"
      sha256 "4d2432cbfbf8386bd137cc0513ed296c28c204d15b119d3d7d733596410086b6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kiwicom/glenv/releases/download/v0.6/glenv_0.6_Linux_x86_64.tar.gz"
      sha256 "ee285f3c94e0f2c87c701e6cfe19a935cc83d7e12b5334787085776225ff34a6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiwicom/glenv/releases/download/v0.6/glenv_0.6_Linux_arm64.tar.gz"
      sha256 "08f77ca2c4eaec841201cc77c602e427813f0ede9adb09d3f9cc53f8eb5683b6"
    end
  end

  def install
    bin.install "glenv"
  end
end
